### ISSUE TITLE
Is it possible to use "youtube-nocookie" for videos?

### ISSUE THREAD

**Issue by Nikslg** [larbisahli/youtube-clone#4]
Hello, I found your clone while looking for an alternative youtube player, and it worked almost perfectly.. except unable to load videos for some reasons.
I am using this client from "blocked" network that doesn't even let VPN to be used.
However, there is one thing that works, that is https://www.youtube-nocookie.com/embed/
I've been using it along with your clone, for awhile now. So I've been wondering, is there a way to somehow combine it? To use player from link above instead of current watch player container?

**Comment by larbisahli** [comment]
Hello, I think you should use this player https://github.com/tjallingt/react-youtube
